section: screens
	archlinux:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		preserveFocus = false
		switchCorners = none 
		switchCornerSize = 0
	NikharvsMacBook:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		preserveFocus = false
		switchCorners = none 
		switchCornerSize = 1
end

section: aliases
end

section: links
	archlinux:
		down = NikharvsMacBook
	NikharvsMacBook:
		up = archlinux
end

section: options
	heartbeat = 1000
	relativeMouseMoves = true
	screenSaverSync = true
	win32KeepForeground = false
	clipboardSharing = true
	clipboardSharingSize = 100000000
	switchCorners = none 
	switchCornerSize = 0
	dragDropSharing = true
end

